### ISSUE TITLE
FR: Add pins

### ISSUE THREAD

**Issue by chrisgrieser** [AlexBieg/obsidian-better-command-palette#2]
Thanks for the plugin! been waiting for a command palette improvement for a while now :)

One thing I actually miss from the original command palette is having pins. Would it be possible to add them, too?

**Comment by AlexBieg** [comment]
I think that should be possible. Ideally, this plugin would be able to make use of the existing pins people have so I'll need to figure out how those are stored. That said I imagine that is fairly trivial. There is also the question of should pins or recently used items be displayed first. I lean towards making that a setting and letting the user decide. Thanks for the request! I'll add it to my queue.

Disclaimer: I'm employed full time so this only gets attention after work. If you need/want this ASAP I'm happy to review a PR 😄 Otherwise I'll get to it as soon as I can.
